#!/usr/bin/env sh
# Regenerate the license bundle shipped with release binaries. cargo-about is a
# maintainer tool, not a build dependency; pin its version when installing it.
set -eu

EXPECTED_VERSION=0.9.1
OUTPUT=THIRD_PARTY_LICENSES.html
DIGEST_OUTPUT=THIRD_PARTY_LICENSES.html.sha256

command -v cargo-about >/dev/null 2>&1 || {
    printf 'install cargo-about %s first: cargo install cargo-about --version %s --locked --features cli\n' \
        "$EXPECTED_VERSION" "$EXPECTED_VERSION" >&2
    exit 1
}
actual=$(cargo-about --version | awk '{print $2}')
[ "$actual" = "$EXPECTED_VERSION" ] || {
    printf 'expected cargo-about %s, found %s\n' "$EXPECTED_VERSION" "$actual" >&2
    exit 1
}

input_hash=$(scripts/license-input-hash.sh)

tmp=$(mktemp "${TMPDIR:-/tmp}/agsh-licenses.XXXXXX")
trap 'rm -f "$tmp" "$tmp.generated"' EXIT INT TERM
cargo-about generate --locked --offline --fail -o "$tmp.generated" about.hbs
awk -v marker="<!-- Generated by cargo-about $EXPECTED_VERSION from release license inputs SHA-256: $input_hash; do not edit. -->" '
    { print }
    NR == 1 { print marker }
' "$tmp.generated" >"$tmp"
mv "$tmp" "$OUTPUT"
rm -f "$tmp.generated"
if command -v sha256sum >/dev/null 2>&1; then
    output_hash=$(sha256sum "$OUTPUT" | awk '{print $1}')
else
    output_hash=$(shasum -a 256 "$OUTPUT" | awk '{print $1}')
fi
printf '%s  %s\n' "$output_hash" "$OUTPUT" >"$DIGEST_OUTPUT"
printf 'generated %s and %s\n' "$OUTPUT" "$DIGEST_OUTPUT"
