#!/usr/bin/env sh
# Static release guard used locally and by the tag workflow. It intentionally
# needs only POSIX tools so it runs before Rust or project dependencies exist.
set -eu

fail() {
    printf 'release validation: %s\n' "$*" >&2
    exit 1
}

version=$(sed -n 's/^version = "\([^"]*\)"/\1/p' Cargo.toml | head -n 1)
rust_version=$(sed -n 's/^rust-version = "\([^"]*\)"/\1/p' Cargo.toml | head -n 1)
toolchain=$(sed -n 's/^channel = "\([^"]*\)"/\1/p' rust-toolchain.toml | head -n 1)

[ -n "$version" ] || fail "workspace version is missing"
[ -n "$rust_version" ] || fail "workspace rust-version is missing"
[ -n "$toolchain" ] || fail "rust-toolchain.toml channel is missing"
[ "${toolchain%.*}" = "$rust_version" ] ||
    fail "rust-version $rust_version and pinned toolchain $toolchain disagree"
for manifest in crates/*/Cargo.toml; do
    grep -F -x -q 'rust-version.workspace = true' "$manifest" ||
        fail "$manifest does not inherit workspace rust-version"
done

license_input_hash=$(scripts/license-input-hash.sh)
CARGO_ABOUT_VERSION=0.9.1
grep -F -q "Generated by cargo-about $CARGO_ABOUT_VERSION from release license inputs SHA-256: $license_input_hash;" THIRD_PARTY_LICENSES.html ||
    fail "THIRD_PARTY_LICENSES.html is stale; run scripts/generate-third-party-licenses.sh"
license_digest_file=THIRD_PARTY_LICENSES.html.sha256
[ -f "$license_digest_file" ] ||
    fail "$license_digest_file is missing; run scripts/generate-third-party-licenses.sh"
expected_license_digest=$(awk '
    NR == 1 && $2 == "THIRD_PARTY_LICENSES.html" && length($1) == 64 && $1 ~ /^[0-9a-f]+$/ { print $1 }
' "$license_digest_file")
[ "$(wc -l <"$license_digest_file" | tr -d ' ')" = 1 ] && [ -n "$expected_license_digest" ] ||
    fail "$license_digest_file is malformed; run scripts/generate-third-party-licenses.sh"
if command -v sha256sum >/dev/null 2>&1; then
    actual_license_digest=$(sha256sum THIRD_PARTY_LICENSES.html | awk '{print $1}')
else
    actual_license_digest=$(shasum -a 256 THIRD_PARTY_LICENSES.html | awk '{print $1}')
fi
[ "$actual_license_digest" = "$expected_license_digest" ] ||
    fail "THIRD_PARTY_LICENSES.html does not match its generated digest; run scripts/generate-third-party-licenses.sh"

bad_sources=$(grep '^source = ' Cargo.lock |
    grep -F -v 'source = "registry+https://github.com/rust-lang/crates.io-index"' || true)
[ -z "$bad_sources" ] || fail "Cargo.lock contains an unapproved package source:
$bad_sources"

# Action tags are mutable. Every external action invocation must use a full,
# lowercase commit object id; the trailing version comment remains updateable by
# Dependabot and readable by maintainers.
action_lines=$(grep -R -h -E '^[[:space:]]*(-[[:space:]]+)?uses:' .github/workflows || true)
[ -n "$action_lines" ] || fail "no GitHub Actions invocations found"
bad_actions=$(printf '%s\n' "$action_lines" |
    grep -E -v 'uses:[[:space:]]+[^[:space:]@]+@[0-9a-f]{40}([[:space:]]+#.*)?$' || true)
[ -z "$bad_actions" ] || fail "unpinned GitHub Action(s):
$bad_actions"

case "${1:-}" in
"") ;;
v*)
    tag=$1
    printf '%s\n' "$tag" |
        grep -E -q '^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$' ||
        fail "tag must be a stable vMAJOR.MINOR.PATCH release tag: $tag"
    [ "$tag" = "v$version" ] ||
        fail "tag $tag does not match workspace version v$version"
    release_heading=$(awk -v prefix="## [$version]" \
        'index($0, prefix) == 1 { print }' CHANGELOG.md)
    [ -n "$release_heading" ] ||
        fail "CHANGELOG.md has no dated [$version] release section"
    case "$release_heading" in
    *'
'*) fail "CHANGELOG.md has multiple [$version] release sections" ;;
    esac
    release_date=${release_heading#"## [$version] - "}
    printf '%s\n' "$release_date" |
        grep -E -q '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' ||
        fail "CHANGELOG.md [$version] heading must use YYYY-MM-DD, not: $release_heading"
    [ "$(git cat-file -t "$tag" 2>/dev/null || true)" = "tag" ] ||
        fail "$tag must be an annotated tag"
    [ "$(git rev-parse "$tag^{commit}")" = "$(git rev-parse HEAD)" ] ||
        fail "$tag does not point at the checked-out release commit"
    git show-ref --verify --quiet refs/remotes/origin/main ||
        fail "origin/main is unavailable; release validation requires a full fetch"
    git merge-base --is-ancestor HEAD refs/remotes/origin/main ||
        fail "$tag does not point at a commit reachable from origin/main"
    ;;
*) fail "release tag must start with v: $1" ;;
esac

printf 'release validation: ok (v%s, Rust %s)\n' "$version" "$toolchain"
